# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "dduportal/boot2docker"

  # l'option auto correct permet de corriger automatiquement si jamais la machine host utilise deja le port 5432
  
  # PostgreSQL NA
  config.vm.network :forwarded_port, guest: 5432, host: 5432, auto_correct: true
  # Geoserver NAT
  config.vm.network :forwarded_port, guest: 8080, host: 8080, auto_correct: true
end
